version: 1
classes:
  - entityDef: ReceiversBlock
    classId:
      - 1
      - 1
    properties:
      - id: userLabel
        targetId:
          level: 1
          index: 6
        datatype: NcString
    methods: []
instances:
  - location: root/receivers-block
    rolePath: receivers
