version: 1
rules:
  - match:
      topicFilter: plant/source/value
    target:
      location: root
      property: value
      onUnresolved: warn
    decode:
      format: raw-string
    transform: []
    reverse:
      topicTemplate: plant/source/value
      writeStrategy: single
      encode:
        format: raw-string
